// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for EventCard documents
 */
interface EventcardDocumentData {
  /**
   * title field in *EventCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eventcard.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *EventCard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventcard.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *EventCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eventcard.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * EventCard document from Prismic
 *
 * - **API ID**: `eventcard`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventcardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EventcardDocumentData>,
    "eventcard",
    Lang
  >;

type FootermenuDocumentDataSlicesSlice = SocialLinksSlice;

/**
 * Content for Footer documents
 */
interface FootermenuDocumentData {
  /**
   * logo_bottom field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.logo_bottom
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_bottom: prismic.ImageField<never>;

  /**
   * logo_uncc field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.logo_uncc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_uncc: prismic.ImageField<never>;

  /**
   * logo_cop28 field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.logo_cop28
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_cop28: prismic.ImageField<never>;

  /**
   * logo_appstore field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.logo_appstore
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_appstore: prismic.ImageField<never>;

  /**
   * logo_googleplay field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.logo_googleplay
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_googleplay: prismic.ImageField<never>;

  /**
   * dowload_app_text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.dowload_app_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dowload_app_text: prismic.KeyTextField;

  /**
   * label_privacy_policy field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.label_privacy_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_privacy_policy: prismic.KeyTextField;

  /**
   * link_privacy_policy field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.link_privacy_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_privacy_policy: prismic.LinkField;

  /**
   * label_accessibility field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.label_accessibility
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_accessibility: prismic.KeyTextField;

  /**
   * link_accessibility field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.link_accessibility
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_accessibility: prismic.LinkField;

  /**
   * label_faq field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.label_faq
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_faq: prismic.KeyTextField;

  /**
   * link_faq field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.link_faq
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_faq: prismic.LinkField;

  /**
   * label_rights_reserved field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.label_rights_reserved
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_rights_reserved: prismic.KeyTextField;

  /**
   * label_assistance field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.label_assistance
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_assistance: prismic.RichTextField;

  /**
   * link_uncc field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.link_uncc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_uncc: prismic.LinkField;

  /**
   * link_appstore field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.link_appstore
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_appstore: prismic.LinkField;

  /**
   * link_googleplay field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.link_googleplay
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_googleplay: prismic.LinkField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FootermenuDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footermenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootermenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FootermenuDocumentData>,
    "footermenu",
    Lang
  >;

type HeadermenuDocumentDataSlicesSlice = HeaderMenuItemSlice;

/**
 * Content for Header documents
 */
interface HeadermenuDocumentData {
  /**
   * logo_white field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.logo_white
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_white: prismic.ImageField<never>;

  /**
   * logo_green field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.logo_green
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_green: prismic.ImageField<never>;

  /**
   * call field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.call
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  call: prismic.ImageField<never>;

  /**
   * search field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.search
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  search: prismic.ImageField<never>;

  /**
   * logo_uncc field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.logo_uncc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_uncc: prismic.ImageField<never>;

  /**
   * accessibility field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.accessibility
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  accessibility: prismic.ImageField<never>;

  /**
   * lowCarbonToggleIcon field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.lowcarbontoggleicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lowcarbontoggleicon: prismic.ImageField<never>;

  /**
   * uncc_link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.uncc_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  uncc_link: prismic.LinkField;

  /**
   * lowcarbontogglelabel field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.lowcarbontogglelabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lowcarbontogglelabel: prismic.KeyTextField;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: headermenu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeadermenuDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `headermenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeadermenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HeadermenuDocumentData>,
    "headermenu",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FilterableEventListSlice
  | CarouselSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | EventcardDocument
  | FootermenuDocument
  | HeadermenuDocument
  | PageDocument;

/**
 * Primary content in *Carousel → Items*
 */
export interface CarouselSliceDefaultItem {
  /**
   * image field in *Carousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Carousel → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CarouselSliceDefaultItem>
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *FilterableEventList → Primary*
 */
export interface FilterableEventListSliceDefaultPrimary {
  /**
   * title field in *FilterableEventList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filterable_event_list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for FilterableEventList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FilterableEventListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FilterableEventListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FilterableEventList*
 */
type FilterableEventListSliceVariation = FilterableEventListSliceDefault;

/**
 * FilterableEventList Shared Slice
 *
 * - **API ID**: `filterable_event_list`
 * - **Description**: FilterableEventList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FilterableEventListSlice = prismic.SharedSlice<
  "filterable_event_list",
  FilterableEventListSliceVariation
>;

/**
 * Primary content in *HeaderMenuItem → Primary*
 */
export interface HeaderMenuItemSliceDefaultPrimary {
  /**
   * label field in *HeaderMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *HeaderMenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *HeaderMenuItem → Items*
 */
export interface HeaderMenuItemSliceDefaultItem {
  /**
   * label field in *HeaderMenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_menu_item.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *HeaderMenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_menu_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for HeaderMenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderMenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderMenuItemSliceDefaultPrimary>,
  Simplify<HeaderMenuItemSliceDefaultItem>
>;

/**
 * Slice variation for *HeaderMenuItem*
 */
type HeaderMenuItemSliceVariation = HeaderMenuItemSliceDefault;

/**
 * HeaderMenuItem Shared Slice
 *
 * - **API ID**: `header_menu_item`
 * - **Description**: HeaderMenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderMenuItemSlice = prismic.SharedSlice<
  "header_menu_item",
  HeaderMenuItemSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SocialLinks → Items*
 */
export interface SocialLinksSliceDefaultItem {
  /**
   * link field in *SocialLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_links.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * icon field in *SocialLinks → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_links.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for SocialLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialLinksSliceDefaultItem>
>;

/**
 * Slice variation for *SocialLinks*
 */
type SocialLinksSliceVariation = SocialLinksSliceDefault;

/**
 * SocialLinks Shared Slice
 *
 * - **API ID**: `social_links`
 * - **Description**: SocialLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialLinksSlice = prismic.SharedSlice<
  "social_links",
  SocialLinksSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EventcardDocument,
      EventcardDocumentData,
      FootermenuDocument,
      FootermenuDocumentData,
      FootermenuDocumentDataSlicesSlice,
      HeadermenuDocument,
      HeadermenuDocumentData,
      HeadermenuDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultItem,
      CarouselSliceVariation,
      CarouselSliceDefault,
      FilterableEventListSlice,
      FilterableEventListSliceDefaultPrimary,
      FilterableEventListSliceVariation,
      FilterableEventListSliceDefault,
      HeaderMenuItemSlice,
      HeaderMenuItemSliceDefaultPrimary,
      HeaderMenuItemSliceDefaultItem,
      HeaderMenuItemSliceVariation,
      HeaderMenuItemSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SocialLinksSlice,
      SocialLinksSliceDefaultItem,
      SocialLinksSliceVariation,
      SocialLinksSliceDefault,
    };
  }
}
