// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carousel: dynamic(() => import("./Carousel")),
  filterable_event_list: dynamic(() => import("./FilterableEventList")),
  header_menu_item: dynamic(() => import("./HeaderMenuItem")),
  rich_text: dynamic(() => import("./RichText")),
  social_links: dynamic(() => import("./SocialLinks")),
};
